while True:
    a = input('1.raju\n2.baju\n3.kaju\n4.haju\nEnter the name from the above list ,\nWhose result you wanna retrieve : ')
    stu0 = 'The results  mentioned below'
    stu1 = 'raju'
    stu2 = 'baju'
    stu3 = 'kaju'
    stu4 = 'haju'
    if stu1 == a:
        print('NAME :  ', a,'\nMATHS : PASS\nSCIENCE : PASS\nSOCIAL : FAIL\nENGLISH : PASS\nKANNADA : PASS\n')
        print('Subject wise class pass percentage :\nMATHS : 100%\nSCIENCE : 75%\nSOCIAL : 50%\nENGLISH : 100%\nKANNADA : 100%\n')
        print('Subject wise class topper :\nMATHS : raju\nSCIENCE : raju\nSOCIAL : baju\nENGLISH : kaju\nKANNADA : raju\n')
        print('Overall Class topper is : Raju')
        break
    elif stu2 == a:
        print('NAME :  ', a,'\nMATHS : PASS\nSCIENCE : FAIL\nSOCIAL : FAIL\nENGLISH : PASS\nKANNADA : PASS\n')
        print('Subject wise class pass percentage :\nMATHS : 100%\nSCIENCE : 75%\nSOCIAL : 50%\nENGLISH : 100%\nKANNADA : 100%\n')
        print('Subject wise class topper :\nMATHS : raju\nSCIENCE : raju\nSOCIAL : baju\nENGLISH : kaju\nKANNADA : raju\n')
        print('Overall Class topper is : Raju')
        break
    elif stu3 == a:
        print('NAME :  ', a,'\nMATHS : PASS\nSCIENCE : PASS\nSOCIAL : PASS\nENGLISH : FAIL\nKANNADA : PASS\n')
        print('Subject wise class pass percentage :\nMATHS : 100%\nSCIENCE : 75%\nSOCIAL : 50%\nENGLISH : 100%\nKANNADA : 100%\n')
        print('Subject wise class topper :\nMATHS : raju\nSCIENCE : raju\nSOCIAL : baju\nENGLISH : kaju\nKANNADA : raju\n')
        print('Overall Class topper is : Raju')
        break
    elif stu4 == a:
        print('NAME :  ', a,'\nMATHS : PASS\nSCIENCE : PASS\nSOCIAL : PASS\nENGLISH : PASS\nKANNADA : PASS\n')
        print('Subject wise class pass percentage :\nMATHS : 100%\nSCIENCE : 75%\nSOCIAL : 50%\nENGLISH : 100%\nKANNADA : 100%\n')
        print('Subject wise class topper :\nMATHS : raju\nSCIENCE : raju\nSOCIAL : baju\nENGLISH : kaju\nKANNADA : raju\n')
        print('Overall Class topper is : Raju')
        break
    else:
        print('', 'the above mentioned name is not from the list\n'
                  'So please enter the name from the list\n')
        continue


